### ISSUE TITLE
make cri-dockerd fatal error: traceback did not unwind completely

### ISSUE THREAD

**Issue by vitvara** [Mirantis/cri-dockerd#405]
I don't know what happened; my computer froze after the error was raised.

FYI: i only installed CUDA toolkit in this PC, and already disable swap.

to reproduce

```
wget https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.21.3.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

go version

git clone https://github.com/Mirantis/cri-dockerd.git
cd cri-dockerd


make cri-dockerd
```

output
```
GOARCH= go build -trimpath -ldflags " -s -w -buildid=`git log -1 --pretty='%h'` -X github.com/Mirantis/cri-dockerd/cmd/version.Version=0.3.12-16-gebd9de06 -X github.com/Mirantis/cri-dockerd/cmd/version.PreRelease=`grep -q dev <<< "0.3.12-16-gebd9de06" && echo "pre" || echo ""` -X github.com/Mirantis/cri-dockerd/cmd/version.GitCommit=`git log -1 --pretty='%h'`" -o cri-dockerd
go: downloading go1.22.0 (linux/amd64)
# text/template
runtime: g284: frame.sp=0xc0035437d8 top=0xc003547fe0
	stack=[0xc003540000-0xc003548000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0xe0e329?, 0x1e4948?})
	runtime/panic.go:1023 +0x5c fp=0xc000113e48 sp=0xc000113e18 pc=0x446e7c
runtime.(*unwinder).finishInternal(0x44e749?)
	runtime/traceback.go:565 +0x12a fp=0xc000113e88 sp=0xc000113e48 pc=0x47456a
runtime.(*unwinder).next(0xc000113f40?)
	runtime/traceback.go:446 +0x29 fp=0xc000113f10 sp=0xc000113e88 pc=0x473dc9
runtime.(*_panic).nextFrame.func1()
	runtime/panic.go:938 +0xa6 fp=0xc000113fc8 sp=0xc000113f10 pc=0x446aa6
runtime.systemstack(0x0)
	runtime/asm_amd64.s:509 +0x4a fp=0xc000113fd8 sp=0xc000113fc8 pc=0x4814ca

goroutine 284 gp=0xc002bc9340 m=3 mp=0xc000100008 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:474 +0x8 fp=0xc0035435d0 sp=0xc0035435c0 pc=0x481468
runtime.(*_panic).nextFrame(0x100008?)
	runtime/panic.go:911 +0x65 fp=0xc003543610 sp=0xc0035435d0 pc=0x4469c5
runtime.(*_panic).start(0x7fefaebb6a68?, 0x100?, 0xc000100008?)
	runtime/panic.go:824 +0x145 fp=0xc003543630 sp=0xc003543610 pc=0x446265
panic({0xd6f600?, 0x146f660?})
	runtime/panic.go:764 +0x128 fp=0xc0035436e0 sp=0xc003543630 pc=0x445ee8
runtime.panicmem(...)
	runtime/panic.go:261
runtime.sigpanic()
	runtime/signal_unix.go:881 +0x378 fp=0xc003543740 sp=0xc0035436e0 pc=0x45fc78
cmd/compile/internal/ssa.(*worklist).addUses(...)
	cmd/compile/internal/ssa/sccp.go:276
cmd/compile/internal/ssa.(*worklist).visitValue.func1()
	cmd/compile/internal/ssa/sccp.go:383 +0x10a fp=0xc0035437d8 sp=0xc003543740 pc=0xa85f0a
cmd/compile/internal/ssa.(*worklist).visitValue(0x0, 0xc003543b68)
	cmd/compile/internal/ssa/sccp.go:484 +0xb2d fp=0xc003543890 sp=0xc0035437d8 pc=0xa85d8d
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 17
	cmd/compile/internal/gc/compile.go:163 +0x247

goroutine 1 gp=0xc0000061c0 m=nil [semacquire]:
runtime.gopark(0xc0000a0808?, 0xc0007e7940?, 0x0?, 0xf2?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0007e7900 sp=0xc0007e78e0 pc=0x449d6e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.semacquire1(0xc001ce38c8, 0x0, 0x1, 0x0, 0x12)
	runtime/sema.go:160 +0x225 fp=0xc0007e7968 sp=0xc0007e7900 pc=0x45cdc5
sync.runtime_Semacquire(0xc000aa8900?)
	runtime/sema.go:62 +0x25 fp=0xc0007e79a0 sp=0xc0007e7968 pc=0x47fac5
sync.(*WaitGroup).Wait(0xc001e05b08?)
	sync/waitgroup.go:116 +0x48 fp=0xc0007e79c8 sp=0xc0007e79a0 pc=0x4a0908
cmd/compile/internal/gc.compileFunctions()
	cmd/compile/internal/gc/compile.go:194 +0x213 fp=0xc0007e7a20 sp=0xc0007e79c8 pc=0xceac93
cmd/compile/internal/gc.Main(0xe2ad18)
	cmd/compile/internal/gc/main.go:303 +0x146a fp=0xc0007e7ef0 sp=0xc0007e7a20 pc=0xcecd0a
main.main()
	cmd/compile/main.go:57 +0xf9 fp=0xc0007e7f50 sp=0xc0007e7ef0 pc=0xd15a99
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc0007e7fe0 sp=0xc0007e7f50 pc=0x44991d
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0007e7fe8 sp=0xc0007e7fe0 pc=0x483301

goroutine 2 gp=0xc000006700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00009afa8 sp=0xc00009af88 pc=0x449d6e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb3 fp=0xc00009afe0 sp=0xc00009afa8 pc=0x449bd3
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009afe8 sp=0xc00009afe0 pc=0x483301
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000006c40 m=nil [GC sweep wait]:
runtime.gopark(0xc000034070?, 0xf532f8?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc00009b750 sp=0xc00009b730 pc=0x449d6e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc000034070)
	runtime/mgcsweep.go:278 +0x94 fp=0xc00009b7c8 sp=0xc00009b750 pc=0x430e74
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc00009b7e0 sp=0xc00009b7c8 pc=0x424805
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009b7e8 sp=0xc00009b7e0 pc=0x483301
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000006e00 m=nil [GC scavenge wait]:
runtime.gopark(0xc0000340c8?, 0x0?, 0xe0?, 0xa8?, 0xc000034070?)
	runtime/proc.go:402 +0xce fp=0xc00009bf78 sp=0xc00009bf58 pc=0x449d6e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.(*scavengerState).park(0x1522d00)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc00009bfa8 sp=0xc00009bf78 pc=0x42e0c9
runtime.bgscavenge(0xc000034070)
	runtime/mgcscavenge.go:653 +0x3c fp=0xc00009bfc8 sp=0xc00009bfa8 pc=0x42e65c
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x25 fp=0xc00009bfe0 sp=0xc00009bfc8 pc=0x4247a5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009bfe8 sp=0xc00009bfe0 pc=0x483301
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc000007340 m=nil [finalizer wait]:
runtime.gopark(0x42d4fc?, 0x550000?, 0x80?, 0x7f?, 0x10?)
	runtime/proc.go:402 +0xce fp=0xc00009a620 sp=0xc00009a600 pc=0x449d6e
runtime.runfinq()
	runtime/mfinal.go:194 +0x107 fp=0xc00009a7e0 sp=0xc00009a620 pc=0x4236a7
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00009a7e8 sp=0xc00009a7e0 pc=0x483301
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:164 +0x3d

goroutine 17 gp=0xc001d32fc0 m=nil [runnable]:
runtime.gopark(0xc001eec7b0?, 0x2?, 0x8?, 0xa0?, 0xc001eec724?)
	runtime/proc.go:402 +0xce fp=0xc001eec5c0 sp=0xc001eec5a0 pc=0x449d6e
runtime.selectgo(0xc001eec7b0, 0xc001eec720, 0x0?, 0x0, 0xd4a4e0?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc001eec6e0 sp=0xc001eec5c0 pc=0x45bd85
cmd/compile/internal/gc.compileFunctions.func3()
	cmd/compile/internal/gc/compile.go:152 +0x125 fp=0xc001eec7e0 sp=0xc001eec6e0 pc=0xceafe5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc001eec7e8 sp=0xc001eec7e0 pc=0x483301
created by cmd/compile/internal/gc.compileFunctions in goroutine 1
	cmd/compile/internal/gc/compile.go:145 +0xe5

goroutine 296 gp=0xc001f02380 m=nil [runnable]:
runtime.gopark(0xc001a8d438?, 0xab2480?, 0xc0?, 0x38?, 0xc001ec84d0?)
	runtime/proc.go:402 +0xce fp=0xc0035b1f40 sp=0xc0035b1f20 pc=0x449d6e
runtime.chansend(...)
	runtime/chan.go:259
runtime.chansend1(0xc001a8d3e0, 0xc0036fe850)
	runtime/chan.go:145 +0x33e fp=0xc0035b1fb0 sp=0xc0035b1f40 pc=0x40a73e
cmd/compile/internal/gc.compileFunctions.func3.1()
	cmd/compile/internal/gc/compile.go:165 +0x3f fp=0xc0035b1fe0 sp=0xc0035b1fb0 pc=0xceb23f
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0035b1fe8 sp=0xc0035b1fe0 pc=0x483301
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 17
	cmd/compile/internal/gc/compile.go:163 +0x247

goroutine 286 gp=0xc0031cf500 m=nil [runnable]:
runtime.mapaccess1_fast32(0xd699e0, 0xc003700c90, 0x42a)
	runtime/map_fast32.go:13 +0x165 fp=0xc00370f6b0 sp=0xc00370f6a8 pc=0x418385
cmd/compile/internal/ssa.(*xposmap).mapFor(...)
	cmd/compile/internal/ssa/xposmap.go:55
cmd/compile/internal/ssa.(*xposmap).get(...)
	cmd/compile/internal/ssa/xposmap.go:73
cmd/compile/internal/ssa.applyRewrite(0xc0036cd1e0, 0xe2b6b0, 0xe2b750, 0x1)
	cmd/compile/internal/ssa/rewrite.go:194 +0x1025 fp=0xc00370fb48 sp=0xc00370f6b0 pc=0x7cdd85
cmd/compile/internal/ssa.opt(0xc0036cd1e0?)
	cmd/compile/internal/ssa/opt.go:9 +0x26 fp=0xc00370fb78 sp=0xc00370fb48 pc=0x79c8a6
cmd/compile/internal/ssa.Compile(0xc0036cd1e0)
	cmd/compile/internal/ssa/compile.go:97 +0xa44 fp=0xc0037138b0 sp=0xc00370fb78 pc=0x745064
cmd/compile/internal/ssagen.buildssa(0xc0016a9200, 0x0)
	cmd/compile/internal/ssagen/ssa.go:575 +0x2869 fp=0xc003713ea0 sp=0xc0037138b0 pc=0xabb529
cmd/compile/internal/ssagen.Compile(0xc0016a9200, 0x0)
	cmd/compile/internal/ssagen/pgen.go:216 +0x3e fp=0xc003713f70 sp=0xc003713ea0 pc=0xab1cfe
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
	cmd/compile/internal/gc/compile.go:182 +0x34 fp=0xc003713fb0 sp=0xc003713f70 pc=0xceae14
cmd/compile/internal/gc.compileFunctions.func3.1()
	cmd/compile/internal/gc/compile.go:164 +0x30 fp=0xc003713fe0 sp=0xc003713fb0 pc=0xceb230
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc003713fe8 sp=0xc003713fe0 pc=0x483301
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 17
	cmd/compile/internal/gc/compile.go:163 +0x247

goroutine 287 gp=0xc0031cf6c0 m=nil [runnable]:
cmd/compile/internal/ssa.CanSSA(0xc000cbe120)
	cmd/compile/internal/ssa/value.go:590 +0x148 fp=0xc001f47c90 sp=0xc001f47c88 pc=0xa986e8
cmd/compile/internal/ssagen.(*state).stmt(0xc003586f00, {0xf656b8, 0xc001c97770})
	cmd/compile/internal/ssagen/ssa.go:1668 +0x6b9b fp=0xc001f48230 sp=0xc001f47c90 pc=0xac7d3b
cmd/compile/internal/ssagen.(*state).stmtList(...)
	cmd/compile/internal/ssagen/ssa.go:1426
cmd/compile/internal/ssagen.(*state).stmt(0xc003586f00, {0xf656b8, 0xc001c97590})
	cmd/compile/internal/ssagen/ssa.go:1441 +0x24f fp=0xc001f487d0 sp=0xc001f48230 pc=0xac13ef
cmd/compile/internal/ssagen.(*state).stmtList(...)
	cmd/compile/internal/ssagen/ssa.go:1426
cmd/compile/internal/ssagen.(*state).stmt(0xc003586f00, {0xf65238, 0xc001c93080})
	cmd/compile/internal/ssagen/ssa.go:1446 +0x64fc fp=0xc001f48d70 sp=0xc001f487d0 pc=0xac769c
cmd/compile/internal/ssagen.(*state).stmtList(...)
	cmd/compile/internal/ssagen/ssa.go:1426
cmd/compile/internal/ssagen.(*state).stmt(0xc003586f00, {0xf656b8, 0xc001c8b720})
	cmd/compile/internal/ssagen/ssa.go:1441 +0x24f fp=0xc001f49310 sp=0xc001f48d70 pc=0xac13ef
cmd/compile/internal/ssagen.(*state).stmtList(...)
	cmd/compile/internal/ssagen/ssa.go:1426
cmd/compile/internal/ssagen.(*state).stmt(0xc003586f00, {0xf658f8, 0xc000f00230})
	cmd/compile/internal/ssagen/ssa.go:1904 +0x55dc fp=0xc001f498b0 sp=0xc001f49310 pc=0xac677c
cmd/compile/internal/ssagen.(*state).stmtList(...)
	cmd/compile/internal/ssagen/ssa.go:1426
cmd/compile/internal/ssagen.buildssa(0xc000e22ea0, 0x2)
	cmd/compile/internal/ssagen/ssa.go:555 +0x25aa fp=0xc001f49ea0 sp=0xc001f498b0 pc=0xabb26a
cmd/compile/internal/ssagen.Compile(0xc000e22ea0, 0x2)
	cmd/compile/internal/ssagen/pgen.go:216 +0x3e fp=0xc001f49f70 sp=0xc001f49ea0 pc=0xab1cfe
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
	cmd/compile/internal/gc/compile.go:182 +0x34 fp=0xc001f49fb0 sp=0xc001f49f70 pc=0xceae14
cmd/compile/internal/gc.compileFunctions.func3.1()
	cmd/compile/internal/gc/compile.go:164 +0x30 fp=0xc001f49fe0 sp=0xc001f49fb0 pc=0xceb230
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc001f49fe8 sp=0xc001f49fe0 pc=0x483301
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 17
	cmd/compile/internal/gc/compile.go:163 +0x247
# github.com/containernetworking/cni/pkg/types/100
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x15c pc=0x704fdb]

goroutine 10 [running]:
cmd/internal/obj/x86.span6(0xc0001b6400, 0xc00096a300, 0xc000aec7e0)
	cmd/internal/obj/x86/asm6.go:2115 +0x45b
cmd/internal/obj.Flushplist(0xc0001b6400, 0xc000157f30, 0xc000aec7e0)
	cmd/internal/obj/plist.go:168 +0xb3a
cmd/compile/internal/objw.(*Progs).Flush(...)
	cmd/compile/internal/objw/prog.go:112
cmd/compile/internal/ssagen.Compile(0xc00068a5a0, 0x3)
	cmd/compile/internal/ssagen/pgen.go:241 +0x6a8
cmd/compile/internal/gc.compileFunctions.func5.1(0x45213d?)
	cmd/compile/internal/gc/compile.go:182 +0x34
cmd/compile/internal/gc.compileFunctions.func3.1()
	cmd/compile/internal/gc/compile.go:164 +0x30
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 8
	cmd/compile/internal/gc/compile.go:163 +0x247
client_loop: send disconnect: Broken pipe
```

**Comment by vitvara** [comment]
I solved the issue by disabling overclocking in the BIOS settings. I'm not sure why overclocking was set as the default by the vendor. I’m using an Intel(R) Core(TM) i9-14900KS.
